### ISSUE TITLE
Version the class

### ISSUE THREAD

**Issue by ahansson89** [tareq1988/wordpress-settings-api-class#21]
Right now I am using this class for multiple projects and I would love if I could see what version my class have compared to the version on github.

**Comment by roidayan** [comment]
My suggestion is to rename the class per plugin I use it with. this is what I do. this is to avoid any conflicts with other plugins that may use older or newer version. sometimes I also have small modifications in the class so this will also avoid problems to the other plugins in case my plugin loads first.

**Comment by ahansson89** [comment]
Why would you want to load the class multiple times for multiple plugins? The cool thing about a class like this is that it can be loaded once and reused in different plugins. Now what I like to do is to use the latest version of the class no matter which plugins that are using it.

**Comment by roidayan** [comment]
because I know I have changes. you can use 1 name for all your plugins as you can track and update the class for all your plugins but I think it should still be different than the default from whats in the git.
Other people might use this class with their changes or not and there might be a collision or bad behavior, etc.

I try to submit the changes I do but for example I added input type url which if my class won't load there will be a problem and a bad behavior.
if my pull request will be accepted then it will be fine but maybe other plugin uses the old class and will be loaded first. then there is still a bad behavior.
that's why my plugin uses a different name.

**Comment by ahansson89** [comment]
So why don't you just rename your class? I really don't get your logic and the big problem here?

**Comment by roidayan** [comment]
There is no problem. That what I said. I renamed the class.

**Comment by ahansson89** [comment]
Well, then it is two different use cases. For other people using this class, without any modifications, they want the WP admin to load the latest version of the class no matter which plugin is using it. This is why I opened this ticket.

**Comment by tareq1988** [comment]
Just added initial composer support ([see readme](https://github.com/tareq1988/wordpress-settings-api-class/)), so you can stay updated. Haven't added the version number yet. Also updated the directory structure. Added changelog too
